import {store} from './store.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={selectedDate:new Date(),filter:'all',search:''}; const pad=n=>String(n).padStart(2,'0'); const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`; const dateFromISO=s=>new Date(`${s}T12:00:00`); const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function selectedISO(){return iso(state.selectedDate)}
function tasksForDate(){return store.data.tasks.filter(t=>t.date===selectedISO())}
function render(){renderHeader();renderWeek();renderTasks();renderTimeline();renderSide();renderSimpleLists()}
function renderHeader(){const d=state.selectedDate;$('#pageTitle').textContent=d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});$('#focusDate').textContent=d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});$('#syncText').textContent=store.mode==='firebase'?'Firebase connected':'Local demo mode';$('#syncDot').classList.toggle('online',store.mode==='firebase')}
function startOfWeek(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function renderWeek(){const start=startOfWeek(state.selectedDate);$('#weekStrip').innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const tasks=store.data.tasks.filter(t=>t.date===iso(d));const done=tasks.filter(t=>t.completed).length;const pct=tasks.length?done/tasks.length*100:0;return `<button class="day-card ${iso(d)===selectedISO()?'selected':''}" data-date="${iso(d)}"><strong>${d.toLocaleDateString(undefined,{weekday:'short'}).toUpperCase()}</strong><span>${d.toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><span>${done}/${tasks.length} done</span><div class="day-progress"><i style="width:${pct}%"></i></div></button>`}).join('');$$('.day-card').forEach(b=>b.onclick=()=>{state.selectedDate=dateFromISO(b.dataset.date);render()})}
function filteredTasks(){return tasksForDate().filter(t=>{const f=state.filter==='all'||(state.filter==='completed'?t.completed:t.priority.toLowerCase()===state.filter);const q=!state.search||`${t.title} ${t.category} ${t.notes}`.toLowerCase().includes(state.search);return f&&q}).sort((a,b)=>(a.completed-b.completed)||(a.startTime||'99:99').localeCompare(b.startTime||'99:99'))}
function renderTasks(){const all=tasksForDate(), list=filteredTasks();$('#countAll').textContent=all.length;$('#countHigh').textContent=all.filter(t=>t.priority==='High').length;$('#countMedium').textContent=all.filter(t=>t.priority==='Medium').length;$('#countLow').textContent=all.filter(t=>t.priority==='Low').length;$('#countDone').textContent=all.filter(t=>t.completed).length;$('#taskList').innerHTML=list.map(t=>`<div class="task-row" data-id="${t.id}"><input class="task-check" type="checkbox" ${t.completed?'checked':''} aria-label="Complete ${esc(t.title)}"><span class="task-title ${t.completed?'done':''}" title="${esc(t.title)}">${esc(t.title)}</span><span class="badge-soft priority-${t.priority.toLowerCase()}">${t.priority}</span><span class="badge-soft category">${esc(t.category)}</span><button class="task-menu" aria-label="Edit ${esc(t.title)}"><i class="bi bi-three-dots-vertical"></i></button></div>`).join('');$('#emptyTasks').classList.toggle('d-none',list.length>0);$$('.task-row').forEach(row=>{const t=store.data.tasks.find(x=>x.id===row.dataset.id);row.querySelector('.task-check').onchange=async e=>{t.completed=e.target.checked;await store.upsert('tasks',t);render();toast(t.completed?'Task completed':'Task reopened')};row.querySelector('.task-menu').onclick=()=>openEdit(t)})}
function renderTimeline(){const tasks=tasksForDate().filter(t=>t.startTime&&!t.completed).sort((a,b)=>a.startTime.localeCompare(b.startTime));$('#timeline').innerHTML=tasks.length?tasks.map(t=>`<div class="time-block"><div class="time-label">${formatTime(t.startTime)}</div><div class="event ${t.priority.toLowerCase()}"><strong>${esc(t.title)}</strong><br><small>${t.estimatedMinutes||30} min · ${esc(t.category)}</small></div></div>`).join(''):`<div class="empty-state"><i class="bi bi-calendar2-check"></i><p>No scheduled tasks for this day.</p></div>`}
function formatTime(v){if(!v)return'';let[h,m]=v.split(':').map(Number);const ap=h>=12?'PM':'AM';h=h%12||12;return `${h}:${pad(m)} ${ap}`}
function renderSide(){const weekStart=startOfWeek(state.selectedDate),weekEnd=new Date(weekStart);weekEnd.setDate(weekEnd.getDate()+7);const wt=store.data.tasks.filter(t=>{const d=dateFromISO(t.date);return d>=weekStart&&d<weekEnd});const done=wt.filter(t=>t.completed).length,pct=wt.length?Math.round(done/wt.length*100):0;$('#progressPercent').textContent=`${pct}%`;$('#progressBar').style.width=`${pct}%`;$('#doneStat').textContent=done;$('#openStat').textContent=wt.length-done;$('#highStat').textContent=wt.filter(t=>t.priority==='High'&&!t.completed).length}
function simple(type,target){$(target).innerHTML=store.data[type].map(x=>`<label class="simple-item"><input type="checkbox" data-type="${type}" data-id="${x.id}" ${x.completed?'checked':''}><span class="${x.completed?'text-decoration-line-through opacity-50':''}">${esc(x.title)}</span></label>`).join('')}
function renderSimpleLists(){simple('goals','#goalList');simple('habits','#habitList');simple('shopping','#shoppingList');$('#notesList').innerHTML=store.data.notes.map(n=>`<div class="note-item"><i class="bi bi-lightbulb"></i><span>${esc(n.title)}</span></div>`).join('');$$('.simple-item input').forEach(c=>c.onchange=async()=>{const x=store.data[c.dataset.type].find(i=>i.id===c.dataset.id);x.completed=c.checked;await store.upsert(c.dataset.type,x);renderSimpleLists()})}
function openEdit(t){$('#taskModalLabel').textContent='Edit task';$('#taskId').value=t.id;$('#taskTitle').value=t.title;$('#taskDate').value=t.date;$('#taskTime').value=t.startTime||'';$('#taskDuration').value=t.estimatedMinutes||30;$('#taskPriority').value=t.priority;$('#taskCategory').value=t.category;$('#taskNotes').value=t.notes||'';bootstrap.Modal.getOrCreateInstance($('#taskModal')).show()}
function resetTaskForm(){ $('#taskForm').reset();$('#taskId').value='';$('#taskDate').value=selectedISO();$('#taskDuration').value=30;$('#taskPriority').value='Medium';$('#taskModalLabel').textContent='Add task';$('#taskError').textContent='' }
async function addSimple(type){const labels={goal:'goal',habit:'habit',note:'note',shopping:'shopping item'};const title=prompt(`Add ${labels[type]}:`)?.trim();if(!title)return;const key=type==='goal'?'goals':type==='habit'?'habits':type==='note'?'notes':'shopping';await store.upsert(key,{id:uid(),title,...(key==='notes'?{}:{completed:false})});render();toast('Added')}
function buildPlan(){const rank={High:0,Medium:1,Low:2};const tasks=tasksForDate().filter(t=>!t.completed).sort((a,b)=>rank[a.priority]-rank[b.priority]||(a.startTime||'99:99').localeCompare(b.startTime||'99:99'));if(!tasks.length){$('#aiResult').innerHTML='<div class="ai-step">Everything for this day is complete.</div>';return}let cursor=8*60+30;$('#aiResult').innerHTML=tasks.slice(0,8).map(t=>{if(t.startTime){const[h,m]=t.startTime.split(':').map(Number);cursor=Math.max(cursor,h*60+m)}const start=cursor,end=cursor+(+t.estimatedMinutes||30);cursor=end+10;return `<div class="ai-step"><strong>${mins(start)}</strong> — ${esc(t.title)} <span class="muted">(${t.priority})</span></div>`}).join('')}
function mins(n){const h=Math.floor(n/60)%24,m=n%60;return `${h%12||12}:${pad(m)} ${h>=12?'PM':'AM'}`}
function bind(){$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');$('#todayBtn').onclick=()=>{state.selectedDate=new Date();render()};$('#prevDay').onclick=()=>{state.selectedDate.setDate(state.selectedDate.getDate()-1);render()};$('#nextDay').onclick=()=>{state.selectedDate.setDate(state.selectedDate.getDate()+1);render()};$('#globalSearch').oninput=e=>{state.search=e.target.value.trim().toLowerCase();renderTasks()};$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;renderTasks()});$$('[data-add]').forEach(b=>b.onclick=()=>addSimple(b.dataset.add));$('#quickNoteBtn').onclick=()=>addSimple('note');$('#planDayBtn').onclick=buildPlan;$('#taskModal').addEventListener('show.bs.modal',e=>{if(!e.relatedTarget?.classList.contains('task-menu')&&!$('#taskId').value)resetTaskForm()});$('#taskModal').addEventListener('hidden.bs.modal',resetTaskForm);$('#taskForm').onsubmit=async e=>{e.preventDefault();const title=$('#taskTitle').value.trim();if(!title){$('#taskError').textContent='Enter a task title.';return}const id=$('#taskId').value||uid();const existing=store.data.tasks.find(t=>t.id===id);const item={id,title,date:$('#taskDate').value,startTime:$('#taskTime').value,estimatedMinutes:+$('#taskDuration').value||30,priority:$('#taskPriority').value,category:$('#taskCategory').value,notes:$('#taskNotes').value.trim(),completed:existing?.completed||false,createdAt:existing?.createdAt||Date.now(),updatedAt:Date.now()};await store.upsert('tasks',item);bootstrap.Modal.getInstance($('#taskModal')).hide();if(item.date===selectedISO())render();else render();toast(existing?'Task updated':'Task added')}}
await store.init();bind();resetTaskForm();render();
